name: "Update Snyk Homebrew formula with latest release"
on: push

jobs:
  brew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Render latest template
        run: |
          ruby render.rb | tee Formula/snyk.rb
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -a -m "Automatically updated to latest Snyk release"
          git push origin master
